### ISSUE TITLE
Not working in Kodi installed in firetstick

### ISSUE THREAD

**Issue by ashoktvm** [elgatito/elementum-surge#1]
Elementum addon not working in Kodi installed in firestick. Working fine on other platforms. Anything to do to make it work. I installed using all platform zip and also tried using arm zip

**Comment by elgatito** [comment]
This repository is for documentation and website only.

If you have problems with addon - you can create an issue in elementum issue tracker with attached log file.
https://github.com/elgatito/plugin.video.elementum/
